apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    #url: http://prometheus:9090
    url: http://34.70.166.89:9090
    basicAuth: false
    isDefault: true
    editable: true
