version: "3.8"
services:
  python-api:
    build: ./Python
    ports:
      - "5000:5000"
    volumes:
      - ./Python:/pythonApi
  go-api:
    build: ./Go
    ports:
      - "8080:8080"
    volumes:
      - ./Go:/goApi